version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/scanner"
    schedule:
      interval: "weekly"
