name: Publish Docker Images 
on:
  push:
    branches: ['main']

jobs:
  push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          cd scanner 
          docker build . --tag ghcr.io/ngn13/massacr/scanner:latest
          docker push ghcr.io/ngn13/massacr/scanner:latest
          
          cd ../api
          docker build . --tag ghcr.io/ngn13/massacr/api:latest
          docker push ghcr.io/ngn13/massacr/api:latest
